Rsa key and new build option
CNRS-UNIC/cloud-deploy pull request #1
Opened 2017-09-20 14:53 UTC by jgonin

2017-09-21 07:12 UTC, jgonin commented
The second part of the build function (using the tags) does not work for me wet. You might want want me to fix this before accepting the pull request.

2017-09-22 09:29 UTC, apdavison requested changes
Nice work!

Just a handful of small formatting changes needed - see details

2017-09-22 09:29 UTC, apdavison commented on cloud_deploy/cli.py
> +            git_tag += "z"
please remove extra space

2017-09-22 09:29 UTC, apdavison commented on cloud_deploy/cli.py
> +                "colour": colour,
please line-up the and following 2 lines with `"git"`

2017-09-22 09:29 UTC, apdavison commented on cloud_deploy/cli.py
> +    if remote == None :
Should be `if remote is None:`

2017-09-22 09:29 UTC, apdavison commented on cloud_deploy/cli.py
> +        logger.info("Pushing project '{}' on the remote machine {} ".format(service, remote ))
should be "pushing ... to" not "pushing ... on"

2017-09-22 09:29 UTC, apdavison commented on cloud_deploy/cli.py
> +        if remote == None :
`is None`

2017-09-22 09:29 UTC, apdavison commented on cloud_deploy/cli.py
> +    if remote == None :
`is None`

2017-09-22 09:29 UTC, apdavison commented on cloud_deploy/nodes.py
> +        while status != "completed":
please remote additional space at end of line

2017-09-22 09:29 UTC, apdavison commented on cloud_deploy/nodes.py
> +                ssh_keys=['66:0b:b5:20:a0:68:f9:fc:82:5a:de:c1:ce:03:4f:84']) #think about what to do with that
Perhaps we should create a config file, where a list of ssh public keys could be included. In the meantime, perhaps just add your key fingerprint to this list
(run `ssh-keygen -E md5 -lf /path/to/your_key.pub` to generate the fingerprint)

2017-09-22 09:29 UTC, apdavison commented on cloud_deploy/nodes.py
> +            if os.path.isfile(os.path.expanduser("~/.ssh/{}".format(key))) == False :
`is False`

2017-09-22 12:56 UTC, apdavison approved these changes

2017-09-22 12:56 UTC, merged